 language: node_js
 node_js:
   - "0.11"
   - "0.10"
 install:
   - "npm install"
 #before_install:
 #  - npm install crypto-js
 branches:
   only:
     - master
 services:
   - mongodb
   - redis-server
 after_success:
  - echo "after_success"
  - chmod 600 .travis/id_rsa.netsight
  - ssh-add .travis/id_rsa.netsight
  - git remote add deploy https://github.com/swarbiv/public-gh-repo
  - git push deploy
